### ISSUE TITLE
Android REST API Client

### ISSUE THREAD

**Issue by JoeyTadisa** [JoeyTadisa/Excursion-Management#13]
We should be able to access data from the data endpoint with regards to all the available excursions.

**Comment by JoeyTadisa** [comment]
I'm not sure if you guys have already seen these guides on the Android Developers site:

- https://developer.android.com/training/volley/simple
- https://developer.android.com/training/volley/requestqueue
- Make a standard request: https://developer.android.com/training/volley/request
- Implement a custom request: https://developer.android.com/training/volley/request-custom

**Comment by cinzia22** [comment]
no, we haven't. We just tried to follow up a youtube tutorial video about the API Client. Thanks Joey.

**Comment by JoeyTadisa** [comment]
Another video that I found 
https://www.youtube.com/watch?v=xHXn3Kg2IQE

**Comment by JoeyTadisa** [comment]
https://code.tutsplus.com/tutorials/android-from-scratch-using-rest-apis--cms-27117
