### ISSUE TITLE
API: destination, date_of_excursion and excursion_fee columns not in excursion table

### ISSUE THREAD

**Issue by charissaabegail** [JoeyTadisa/Excursion-Management#37]
**In remote database:**
<img width="261" alt="Bildschirmfoto 2021-11-26 um 20 23 30" src="https://user-images.githubusercontent.com/16249067/143623338-294fc83e-d70e-401e-9996-21021447a684.png">

**In api model with setters and getters:**
<img width="276" alt="Bildschirmfoto 2021-11-26 um 20 28 34" src="https://user-images.githubusercontent.com/16249067/143623653-b7ef0abc-d189-49bb-893f-971368e0c1b4.png">

**TESTING**

**1. Fetch all excursions**
endpoint: http://127.0.0.1:9191/excursions
<img width="949" alt="Bildschirmfoto 2021-11-26 um 20 30 03" src="https://user-images.githubusercontent.com/16249067/143623762-85e136f2-e6e7-43d9-93ec-104593626a58.png">

**2. Fetch all approved or not yet approved excursions**
endpoint: http://localhost:9191/approvedExcursions/true
<img width="1000" alt="Bildschirmfoto 2021-11-26 um 20 30 54" src="https://user-images.githubusercontent.com/16249067/143623814-88045f83-9a67-46ab-99c8-d320c8abfc83.png">

**3. Adding of Excursions**
endpoint: http://localhost:9191/addExcursion
body:
<img width="842" alt="Bildschirmfoto 2021-11-26 um 20 31 57" src="https://user-images.githubusercontent.com/16249067/143623867-cb2d9b66-c024-4331-8eb4-ab4706e1dbc5.png">
table result:
<img width="843" alt="Bildschirmfoto 2021-11-26 um 20 32 23" src="https://user-images.githubusercontent.com/16249067/143623896-6a584bfc-3b51-44f5-bc71-60bc34a8593d.png">
<img width="562" alt="Bildschirmfoto 2021-11-26 um 20 32 35" src="https://user-images.githubusercontent.com/16249067/143623910-5b68c36b-bc02-419e-a654-f5b38f21f3c6.png">

**3. Approving of Excursions request**
endpoint: http://localhost:9191/approveExcursion
<img width="689" alt="Bildschirmfoto 2021-11-26 um 20 38 35" src="https://user-images.githubusercontent.com/16249067/143624255-d9a5c530-2e42-4736-ac7a-bc1f333f4968.png">

excursion id 25 got approved (is_approved from 0 to 1) dateReviewed has been updated
<img width="549" alt="Bildschirmfoto 2021-11-26 um 20 38 55" src="https://user-images.githubusercontent.com/16249067/143624272-12bdbf06-40d2-4ad8-bb59-976cbb43f397.png">

**Comment by JoeyTadisa** [comment]
Internal Server Error caused by missing excursion_fee column in the database dump file (version 5)
![Bildschirmfoto 2021-11-26 um 21 34 01](https://user-images.githubusercontent.com/52509544/143628211-afa80005-83d8-420d-8c2b-48b14884db86.png)

**Comment by JoeyTadisa** [comment]
I re-did the tests and they all passed! :)
