### ISSUE TITLE
App doesn't launch and further issues

### ISSUE THREAD

**Issue by cinzia22** [JoeyTadisa/Excursion-Management#61]
So for now I only created the Appbar with 3 dropdown items. 

1. I wanted to add icons near the items,but the icons are not showing. 
2. Also when I put the AppBar in the excursionlist.xml, the spinner get  covered by the Appbar.
3. Additionally, the app crashes,after being built, so I can't see if the Appbar is showing or not.
4. I still didn't create intents
I only saw now that patrik made a commit, I still didn't pull his changes in my own local  machine

I only saw now that patrik made a commit, I still didn't pull his changes in my own local  machine

[THUExcursionApp.zip](https://github.com/JoeyTadisa/Excursion-Management/files/7636450/THUExcursionApp.zip)
e.

**Comment by JoeyTadisa** [comment]
Ok let me take a look
