### ISSUE TITLE
Booking: Date deregistered

### ISSUE THREAD

**Issue by JoeyTadisa** [JoeyTadisa/Excursion-Management#66]
Related to PR #53 

## SQL error when date deregistered is null
![Bildschirmfoto 2021-12-06 um 10 12 57](https://user-images.githubusercontent.com/52509544/144819416-83502b68-57d0-4aff-bfd2-85feb5580c8f.png)

![Bildschirmfoto 2021-12-06 um 10 13 24](https://user-images.githubusercontent.com/52509544/144819424-346a7d65-42ac-4a13-be06-8bddcda95ebc.png)
![Bildschirmfoto 2021-12-06 um 10 13 17](https://user-images.githubusercontent.com/52509544/144819431-8046b8ce-5b0b-4aca-ae7b-94c73bd41df2.png)

Here is the JSON code that I used to test...
{
  "id": 7,
  "date_booked": "2021-12-06T09:01:30.859Z",
  "booked_by": 4,
  "id_excursion": 23,
  "is_deregistered": false,
  "date_deregistered": "null"
}

## Database references:

![Bildschirmfoto 2021-12-06 um 10 17 00](https://user-images.githubusercontent.com/52509544/144819782-63773f24-f48a-4471-96f1-76881d024a3a.png)

![Bildschirmfoto 2021-12-06 um 10 17 28](https://user-images.githubusercontent.com/52509544/144819838-952a0ba0-0415-42fc-b45a-0ba29c91887b.png)

**Comment by charissaabegail** [comment]
parameters accepted for the endpoint found here: 
https://docs.google.com/spreadsheets/d/1AmI0i4jpWZ0SagbOQG98CmoCdYQxS42wcSxMQP_a1RI/edit?userstoinvite=mafukidzejoey%40gmail.com#gid=0

**Comment by JoeyTadisa** [comment]
Issue was caused by me using user_id instead of student number.

**Comment by charissaabegail** [comment]
I just updated the shared folder and put comment that it should be user_number instead of user_id
